/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cpllegefp;

/**
 *
 * @author lopa
 */
public class bharti extends javax.swing.JFrame {

    String msgg="Bharati Vidyapeeth's College of Engineering (BVCOE) is an engineering college in Paschim Vihar, New Delhi, India. It is approved by All India \nCouncil for Technical Education (AICTE), Ministry of Human Resource Development,\n Government of India.[1] The college was established in year 1999.\n Its parent body is Bharati Vidyapeeth University,a Deemed University in Pune,\n Maharashtra. It is affiliated to Guru Gobind Singh Indraprastha University, Delhi\nBharati vidyapeeth’s college of Engineering is one of the best Engineering college of\n IP University, has 100 percent placement record. College is affiliated to\n IP University and approved by AICTE. Admission in this college is done on the basis of \nEntrance exam conducted by IP University. Currently college has 360\n seats for B.Tech courses.\n" +
"BRANCHES:\n" +
"\n" +
"          •         Information Technology : 60\n" +
"•         Electrical & Electronics Engineering : 60\n" +
"•         Electronics & Communication Engineering : 120\n" +
"•         Computer Science & Engineering  : 60\n" +
"•         Electronics & Instrumentation Engineering  : 60"; 
    public bharti() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\lopa\\Desktop\\bvp.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(190, 50, 250, 162);

        jLabel3.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel3.setText("Bharti Vidyapeeth college of engineering");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 252, 590, 40);

        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 350, 690, 330);

        jLabel5.setText("Admission Criteria: IPCET");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 690, 140, 14);

        jLabel6.setText("Intake: 360 students are enrolled every year. Annual intake is 60 for each branch except ECE which takes 120 students. ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(70, 720, 590, 14);

        jLabel7.setText("Fees: 85000/-");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(80, 750, 80, 14);

        jLabel8.setText(" Address: A-4, Paschim Vihar, Main Rohtak Road, Opposite Ordinance Depot,,Delhi,Delhi NCR - 110063");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(70, 780, 510, 14);

        jLabel9.setText("Phone: 011 - 25278443, 25278444, 25258637");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(70, 810, 240, 14);

        jLabel10.setText(" Email: coedelhi@bharatividyapeeth.edu");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(70, 840, 200, 14);

        jLabel11.setText("Website: www.bvcoend.ac.in");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(70, 870, 150, 14);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(70, 900, 55, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 947, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cpf2 bb= new cpf2();
        bb.show();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bharti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bharti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bharti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bharti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bharti().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
